export { default as outerLogo } from '../../assets/outer-logo.png';
export { default as innerLogo } from '../../assets/inner-logo.png';
export { default as notification } from '../../assets/notification.png';
export { default as searchIcon } from '../../assets/search-icon.png';
export { default as ajiboye } from '../../assets/Ajiboye.png';
export { default as status } from '../../assets/Status.png';
export { default as home } from '../../assets/home.png';
export { default as hamburger } from '../../assets/hamburger.png';
export { default as bubble } from '../../assets/bubble.png';
export { default as settings } from '../../assets/settings.png';
export { default as logout } from '../../assets/logout.png';
export { default as answerIcon } from '../../assets/ANSWER-ICON.png';
export { default as shareIcon } from '../../assets/SHARE-ICON.png';
export { default as arrowUp } from '../../assets/arrow-up.png';
export { default as arrowDown } from '../../assets/arrow-down.png';
export { default as star } from '../../assets/star.png';
export { default as adaeze } from '../../assets/adaeze.png';
export { default as ellipse1 } from '../../assets/Ellipse 1.png';
export { default as ellipse2 } from '../../assets/Ellipse 2.png';
export { default as ellipse3 } from '../../assets/Ellipse 3.png';
export { default as ellipse4 } from '../../assets/Ellipse 4.png';
export { default as ellipse5 } from '../../assets/Ellipse 5.png';
export { default as ellipse6 } from '../../assets/Ellipse 6.png';
export { default as undoLeft } from '../../assets/undo-left.png';
export { default as undoRight } from '../../assets/undo-right.png';
export { default as text } from '../../assets/text.png';
export { default as arrowDown2 } from '../../assets/arrow-down (2).png';
export { default as justify } from '../../assets/justify.png';
export { default as bold } from '../../assets/bold.png';
export { default as italics } from '../../assets/italics.png';
export { default as underline } from '../../assets/italics.png';
export { default as linethrough } from '../../assets/linethrough.png';
export { default as tag } from '../../assets/tag.png';
export { default as erase } from '../../assets/erase.png';
export { default as bullet } from '../../assets/bullet.png';
export { default as numbering } from '../../assets/numbering.png';
export { default as thumbnail } from '../../assets/thumbnail.png';
export { default as link } from '../../assets/link.png';
export { default as closeTag } from '../../assets/close-tag.png';
export { default as quote } from '../../assets/quote.png';
export { default as dash } from '../../assets/dash.png';
